# Copyright 2015 Google Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

sudo: required

services:
  - docker

branches:
  only:
    - master

env:
  globals:
    - GCLOUD_DIR=${HOME}/gcloud
    - PATH=${GCLOUD_DIR}/google-cloud-sdk/bin:${PATH}
    - GOOGLE_APPLICATION_CREDENTIALS=$TRAVIS_BUILD_DIR/credentials.json
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

before_install:
- sudo apt-get update
- sudo apt-get install -y php5-cli
- curl -sS https://getcomposer.org/installer | sudo php -- --install-dir=/usr/local/bin --filename=composer
- wget http://get.sensiolabs.org/php-cs-fixer.phar -O php-cs-fixer
- sudo mv php-cs-fixer /usr/local/bin
- sudo chmod +x /usr/local/bin/php-cs-fixer
# We want to fail fast for coding standard violations.
- php-cs-fixer fix --dry-run --diff --level=psr2 --fixers=concat_with_spaces .
- if [ ! -d ${HOME}/gcloud/google-cloud-sdk ]; then
      mkdir -p ${HOME}/gcloud &&
      wget https://dl.google.com/dl/cloudsdk/release/google-cloud-sdk.tar.gz --directory-prefix=${HOME}/gcloud &&
      cd ${HOME}/gcloud &&
      tar xzf google-cloud-sdk.tar.gz &&
      ./google-cloud-sdk/install.sh --usage-reporting false --path-update false --command-completion false &&
      cd ${TRAVIS_BUILD_DIR};
  fi
- gcloud -q components update app gsutil
- gcloud config set project ${GOOGLE_PROJECT_ID}
- docker build -t php-nginx php-nginx
- docker build -t php56 testapps/php56
- docker build -t php56_custom testapps/php56_custom
- docker build -t php70 testapps/php70

install:
- composer install

script:
- vendor/bin/phpunit && e2e/run_e2e_tests.sh
